[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "git-introduction"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.4.6,<5"
python = "3.13.*"
nbdime = ">=4.0.2,<5"
jupyterlab_code_formatter = ">=3.0.2,<4"
jupyter-resource-usage = ">=1.2.0,<2"
isort = ">=6.0.1,<7"
black = ">=25.1.0,<26"
bash_kernel = ">=0.10.0,<0.11"
bash-language-server = ">=5.6.0,<6"
jupyterlab-myst = ">=2.4.2,<3"

[environments]
win-64 = []
osx-arm64 = []
